name: 'Enigma Docker Build and Publish'
description: 'Builds, scans, tags, and pushes Docker images using the Enigma tool'
inputs:
  command:
    description: 'Command to run (bake or publish)'
    required: true
  DOCKER_IMAGE:
    description: 'Docker image name'
    required: true
  DOCKER_TAG:
    description: 'Docker image tag'
    required: true
  CLEANUP:
    description: 'Cleanup after push (true or false)'
    required: false
    default: 'true'
  # AWS_ACCESS_KEY_ID:
  #   description: 'AWS Access Key ID'
  #   required: true
  # AWS_SECRET_ACCESS_KEY:
  #   description: 'AWS Secret Access Key'
  #   required: true
  # AWS_REGION:
  #   description: 'AWS Region'
  #   required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
    DOCKER_TAG: ${{ inputs.DOCKER_TAG }}
    CLEANUP: ${{ inputs.CLEANUP }}
    # AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
    # AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    # AWS_REGION: ${{ inputs.AWS_REGION }}
  args:
    - ${{ inputs.command }}