name: 'Enigma Docker Build and Publish'
description: 'Builds, scans, tags, and pushes Docker images using the Enigma tool'

inputs:
  command:
    description: 'Command to run (bake or publish)'
    required: true
  DOCKER_IMAGE:
    description: 'Docker image name'
    required: true
  DOCKER_TAG:
    description: 'Docker image tag'
    required: true
  CLEANUP:
    description: 'Cleanup after push (true or false)'
    required: false
    default: 'false'
  AWS_REGION:
    description: 'AWS Region'
    required: false
  AWS_ACCOUNT_ID:
    description: 'AWS Account ID'
    required: false
  GCP_PROJECT_ID:
    description: 'GCP Project ID'
    required: false
  GCP_REGION:
    description: 'GCP Region'
    required: false
  GCLOUD_AUTH:
    description: 'Google Cloud service account key (JSON)'
    required: false
  DOCKER_USERNAME:
    description: 'Docker Hub username'
    required: false
  DOCKER_PASSWORD:
    description: 'Docker Hub password'
    required: false
  TOKEN: 
    description: 'GitHub Token'
    required: false
  GITHUB_USERNAME: 
    description: 'GitHub Username'
    required: false
  GCP_SERVICE_ACCOUNT_EMAIL:
    description: 'Service Account Mail'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
    DOCKER_TAG: ${{ inputs.DOCKER_TAG }}
    AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
    AWS_REGION: ${{ inputs.AWS_REGION }}
    GCP_PROJECT_ID: ${{ inputs.GCP_PROJECT_ID }}
    GCP_REGION: ${{ inputs.GCP_REGION }}
    GCLOUD_AUTH: ${{ inputs.GCLOUD_AUTH }}
    CLEANUP: ${{ inputs.CLEANUP }}
    DOCKER_USERNAME: ${{ inputs.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ inputs.DOCKER_PASSWORD }}
    TOKEN: ${{ inputs.TOKEN }}
    GITHUB_USERNAME: ${{ inputs. GITHUB_USERNAME }}
    GCP_SERVICE_ACCOUNT_EMAIL: ${{ inputs.GCP_SERVICE_ACCOUNT_EMAI }}

  args:
    - ${{ inputs.command }}
