name: Build
on:
  push:
    branches:
      - "**"

env:
  GO_VERSION: 1.23

jobs:
  build:
    name: Run checks and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Format Code with go fmt
        run: go fmt ./...

      - name: Vet
        run: make vet

      - name: Test with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Ensure the token is referenced
          file: ./coverage.out
          flags: unittests
          name: Codecov
          fail_ci_if_error: true

      - name: Build
        run: make
