name: Docker Build and Publish

on:
  push:
    branches:
      - feat/github-action
  workflow_dispatch:

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Scan Docker Image
        uses: ./
        with:
          command: bake
          DOCKER_IMAGE: hello-custom-workflow
          DOCKER_TAG: shivamkumar28dec/enigma:v0
          CLEANUP: 'false'

      - name: Publish Docker Image
        uses: ./
        with:
          command: publish
          DOCKER_IMAGE: hello-custom-workflow
          DOCKER_TAG: shivamkumar28dec/enigma:v0
          CLEANUP: 'false'